# Generated by Django 5.0.1 on 2024-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(to='blogapp.tag')),
            ],
        ),
    ]
