# Generated by Django 5.0.1 on 2024-03-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('coreobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.coreobject')),
                ('description', models.TextField()),
            ],
            bases=('blogapp.coreobject',),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('coreobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.coreobject')),
                ('text', models.TextField()),
            ],
            bases=('blogapp.coreobject',),
        ),
    ]
