# Generated by Django 5.0.1 on 2024-03-08 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_coreobject_search_alter_post_update_car_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='update',
            field=models.TextField(blank=True),
        ),
    ]
