# Generated by Django 5.0.1 on 2024-04-28 06:55

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_tag_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
