# Generated by Django 5.0.1 on 2024-01-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.IntegerField(blank=True)),
            ],
        ),
    ]
