# Generated by Django 5.0.1 on 2024-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_measurement_watersupply_delete_water_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(default='2022-01-01'),
            # Установите значение по умолчанию в формате ISO 8601 или другое предпочтительное
        ),
    ]
