# Generated by Django 5.0.1 on 2024-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupply',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='watersupply',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
