# Generated by Django 5.0.1 on 2024-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_watersupply_date_alter_watersupply_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(default='2024-21-01'),
        ),
    ]
