# Generated by Django 5.0.1 on 2024-01-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watersupply',
            name='name',
        ),
        migrations.AddField(
            model_name='watersupply',
            name='indicators',
            field=models.IntegerField(blank=True, default=55, max_length=255),
            preserve_default=False,
        ),
    ]
