# Generated by Django 5.0.1 on 2024-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_remove_watersupply_name_watersupply_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupply',
            name='indicators',
            field=models.IntegerField(blank=True),
        ),
    ]
