# Generated by Django 5.0.1 on 2024-01-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_alter_watersupply_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicators', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='SuspendedMatter',
            field=models.ForeignKey(default=(3, 14), on_delete=django.db.models.deletion.CASCADE, to='blogapp.suspendedmatter'),
            preserve_default=False,
        ),
    ]
