# Generated by Django 5.0.1 on 2024-01-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_suspendedmatter_measurement_suspendedmatter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
