# Generated by Django 5.0.1 on 2024-01-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_delete_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuspendedMatter',
        ),
    ]
