# Generated by Django 5.0.1 on 2024-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_delete_suspendedmatter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterSupply',
        ),
    ]
